[pt]
  title = "Museu do ICMC"
  languageName = "Português"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/br"
  
[en]
  title = "ICMC Museu"
  languageName = "English"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/en"
