[[main]]
  identifier = "Sobre"
  name = "Sobre"
  url = "Sobre"
  weight = 1

[[main]]
  identifier = "Arquivos"
  name = "Arquivos"
  url = "Arquivos"
  weight = 2

[[main]]
  identifier = "Aprensentação"
  name = "Pt"
  url = "Aprensentação"
  weight = 3

[[main]]
  identifier = "Galeria"
  name = "Galeria"
  url = "Galeria"
  weight = 4
    
[[main]]
  parent = "Galeria"
  name = "Imagens"
  url = "Galeria/Imagens"

[[main]]
  parent = "Galeria"
  name = "Fotos"
  url = "Galeria/Fotos"

[[main]]
  identifier = "Posts"
  name = "Posts"
  url = "Posts"
  weight = 5

[[main]]
  identifier = "SHOWCASE"
  name = "SHOWCASE"
  url = "SHOWCASE"
  weight = 6

[[main]]
  identifier = "Publicações"
  name = "Publicações"
  url = "Publicações"
  weight = 7